#!/usr/bin/python3
import pigpio
import time

servo = 12

# more info at http://abyz.me.uk/rpi/pigpio/python.html#set_servo_pulsewidth

pwm = pigpio.pi()
pwm.set_mode(servo, pigpio.OUTPUT)

pwm.set_PWM_frequency( servo, 50 )

#print(pwm.get_servo_pulsewidth(servo))
init = 1600
while init < 2500:
    pwm.set_servo_pulsewidth( servo, init) ;
    print(init,pwm.get_servo_pulsewidth(servo))
    init += 100
    time.sleep(0.1)
# 
# print( "0 deg" )
# pwm.set_servo_pulsewidth( servo, 500 ) ;
# time.sleep( 3 )
# 
# print( "90 deg" )
# pwm.set_servo_pulsewidth( servo, 1500 ) ;
# #pwm.set_PWM_dutycycle( servo, 10 ) ;
# time.sleep( 3 )
# 
# print( "180 deg" )
# pwm.set_servo_pulsewidth( servo, 2500 ) ;
# #pwm.set_PWM_dutycycle( servo, 30 ) ;
# time.sleep( 3)

# turning off servo
pwm.set_PWM_dutycycle( servo, 0 )
pwm.set_PWM_frequency( servo, 0 ) 
